name: shooter
main: com.github.ucchyocean.Shooter
version: 1.1.1
author: ucchy
description: Shooter is the magic battle item.
commands:
  shooter:
    description: Shooter is the magic battle item.
    aliases: sh
    usage: |
           /<command> get [level] - Get new shooter.
           /<command> give (player) [level] - Give new shooter.
    permission: shooter
    permission-message: You don't have permission "<permission>".
permissions:
  shooter:
    description: Shooter get permission.
    default: true
